CREATE DATABASE php_mysql_crud;

use php_mysql_crud;

CREATE TABLE task(
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users(
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  usuario VARCHAR(50) NOT NULL,
  clave VARCHAR(20) NOT NULL,
  cargo VARCHAR(15) DEFAULT 'alumno',
  privilegio VARCHAR(2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DESCRIBE task;
